### ISSUE TITLE
Error: on Homebridge 1.3.0 beta10

### ISSUE THREAD

**Issue by andyblac** [gawindx/homebridge-risco-platform#16]
just a heads up

```
[10/8/2020, 12:56:49] [RiscoAlarm] Error on RiscoCPBaseDetectors/getCurrentState:
Error: characteristic value expected boolean and received object
    at Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1055:17)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:745:24
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at RiscoCPDetectors.getCurrentState (/usr/lib/node_modules/homebridge-risco-platform/RiscoAccessories.js:625:17)
    at Characteristic.emit (events.js:223:5)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:731:14
    at new Promise (<anonymous>)
    at Characteristic.handleGetRequest (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:729:12)
    at Characteristic.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1227:33)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:140:27)
```

**Comment by gawindx** [comment]
That's good, I haven't had time lately to work on the project and I had to get back to it.
The bug is taken into account.

**Comment by gawindx** [comment]
The problem is corrected and the repository is up to date.
I haven't released the npm yet because I would like to edit a few things before.

If Homebridge 1.3 becomes the stable version (I haven't looked for its relaease date yet), I could release the npm right away.

I added a small functionality for the Bypass of detectors directly from Homekit as well as some improvements in error handling.

**Comment by gawindx** [comment]
the npm package is updated to v1.1.6 and contains this fix.
I close the exit, do not hesitate to reopen it if necessary
