### ISSUE TITLE
errors since 5.4 risco update

### ISSUE THREAD

**Issue by andyblac** [gawindx/homebridge-risco-platform#26]
here is a homebridge log since the Risco 5.4 update, lots of errors, but it still seems to set / unset ok in homekit.

[homebridge.log](https://github.com/gawindx/homebridge-risco-platform/files/5520715/homebridge.log)

example:
```
[37m[10/11/2020, 22:17:30] [39m[36m[RiscoAlarm] [39m[31mUserCodeExpired error:[39m
[31mBad HTTP Response: 500[39m
[31mData: StackExchange.Redis.RedisTimeoutException: Timeout awaiting response (outbound=0KiB, inbound=2KiB, 10610ms elapsed, timeout is 10000ms), command=EVAL, next: EVAL, inst: 0, qu: 0, qs: 22, aw: False, rs: ReadAsync, ws: Idle, in: 0, serverEndpoint: RCWEPRD03-RED01.redis.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: RCWEPRD03-IIS05, IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=1,Free=32766,Min=2,Max=32767), v: 2.1.58.34321 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)[39m
[31m   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisExtensions.HashMemberGetAsync(IDatabase cache, String key, String[] members)[39m
[31m   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.GetAndRefreshAsync(String key, Boolean getData, CancellationToken token)[39m
[31m   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.GetAsync(String key, CancellationToken token)[39m
[31m   at Microsoft.AspNetCore.Session.DistributedSession.LoadAsync(CancellationToken cancellationToken)[39m
[31m   at WebUserUI.WrappedDistributedSession.LoadAsync(CancellationToken cancellationToken) in C:\BuildWS\workspace\RiscoCloud\riscocloud\release\WebUserUI\src\WrappedSession.cs:line 36[39m
[31m   at WebUICore.SessionHelpers.SessionGetAsync[T](HttpContext context, String key) in C:\BuildWS\workspace\RiscoCloud\riscocloud\release\WebUserUI\src\SessionHelpers.cs:line 32[39m
[31m   at WebUserUI.Models.UserData.GetCurrent(HttpContext context) in C:\BuildWS\workspace\RiscoCloud\riscocloud\release\WebUserUI\Models\UserData.cs:line 68[39m
[31m   at WebUserUI.Controllers.SystemSettings.SystemSettingsController.IsUserCodeExpired() in C:\BuildWS\workspace\RiscoCloud\riscocloud\release\WebUserUI\Controllers\SystemSettings\SystemSettingsController.cs:line 1469[39m
[31m   at lambda_method(Closure , Object )[39m
```

**Comment by Sylanorr** [comment]
Hi, 

I have an other error since this morning

[2020-11-11 8:00:07] [RiscoAlarm] Error on getCPStates: TypeError: Cannot read property 'type' of undefined
    at RiscoPanelSession.getPartsStates (/usr/lib/node_modules/homebridge-risco-platform/Risco.js:1100:55)
    at RiscoPanelSession.UpdateCPStates (/usr/lib/node_modules/homebridge-risco-platform/Risco.js:1361:28)
    at RiscoPanelSession.getCPStates (/usr/lib/node_modules/homebridge-risco-platform/Risco.js:1342:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at RiscoPanelSession.getCPStatesPoll (/usr/lib/node_modules/homebridge-risco-platform/Risco.js:1286:16)
(node:23169) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of undefined
    at RiscoPanelSession.getPartsStates (/usr/lib/node_modules/homebridge-risco-platform/Risco.js:1100:55)
    at RiscoPanelSession.UpdateCPStates (/usr/lib/node_modules/homebridge-risco-platform/Risco.js:1361:28)
    at RiscoPanelSession.getCPStates (/usr/lib/node_modules/homebridge-risco-platform/Risco.js:1342:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at RiscoPanelSession.getCPStatesPoll (/usr/lib/node_modules/homebridge-risco-platform/Risco.js:1286:16)
(node:23169) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 326)

**Comment by gawindx** [comment]
it was to be expected.

I will investigate this today and try to deploy a fix soon.

**Comment by gawindx** [comment]
After checking my logs, it seems that the problem solved itself.

I was able to observe this problem until around 12:30 am last night and since 1:00 am the plugin is working correctly again.
Moreover, these errors come, not from the plugin, but from the RiscoCloud server (Error 500 Microsoft ASP Net). So nothing to do with the plugin code.

I think the cloud update must have had some errors that Risco had to correct during normal operations.

@andyblac, Are you still encountering this error?

@Sylanorr, you opened issue #27 regarding your issue, and it seems to me that the issue you are experiencing has nothing to do with updating the RiscoCloud.
I will therefore not answer on this thread but I will come back to you on the issue you have opened.

**Comment by andyblac** [comment]
> After checking my logs, it seems that the problem solved itself.
> 
> I was able to observe this problem until around 12:30 am last night and since 1:00 am the plugin is working correctly again.
> Moreover, these errors come, not from the plugin, but from the RiscoCloud server (Error 500 Microsoft ASP Net). So nothing to do with the plugin code.
> 
> I think the cloud update must have had some errors that Risco had to correct during normal operations.
> 
> @andyblac, Are you still encountering this error?

yes, seems ok now,

**Comment by andyblac** [comment]
back again
```
[11/11/2020, 23:02:33] [RiscoAlarm] Error on getCPStates: Bad HTTP Response: 500
Data: StackExchange.Redis.RedisTimeoutException: Timeout awaiting response (outbound=0KiB, inbound=20KiB, 10594ms elapsed, timeout is 10000ms), command=EVAL, next: EVAL, inst: 0, qu: 0, qs: 15, aw: False, rs: ReadAsync, ws: Idle, in: 0, serverEndpoint: RCWEPRD03-RED01.redis.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: RCWEPRD03-IIS06, IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=1,Free=32766,Min=2,Max=32767), v: 2.1.58.34321 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisExtensions.HashMemberGetAsync(IDatabase cache, String key, String[] members)
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.GetAndRefreshAsync(String key, Boolean getData, CancellationToken token)
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.GetAsync(String key, CancellationToken token)
   at Microsoft.AspNetCore.Session.DistributedSession.LoadAsync(CancellationToken cancellationToken)
   at WebUserUI.WrappedDistributedSession.LoadAsync(CancellationToken cancellationToken) in C:\BuildWS\workspace\RiscoCloud\riscocloud\release\WebUserUI\src\WrappedSession.cs:line 36
   at WebUICore.SessionHelpers.SessionGetAsync[T](HttpContext context, String key) in C:\BuildWS\workspace\RiscoCloud\riscocloud\release\WebUserUI\src\SessionHelpers.cs:line 32
   at WebUserUI.Models.UserData.GetCurrent(HttpContext context) in C:\BuildWS\workspace\RiscoCloud\riscocloud\release\WebUserUI\Models\UserData.cs:line 68
   at WebUserUI.Controllers.Security.SecurityController.GetCPState(Boolean userIsAlive) in C:\BuildWS\workspace\RiscoCloud\riscocloud\release\WebUserUI\Controllers\Security\SecurityController.cs:line 551
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Accept: application/json, text/plain, */*
Connection: close
Content-Length: 2
Content-Type: application/json;charset=utf-8
Cookie: ["RUCCookie=0owz3fEDm8P9ZO7yPKwGCv1%2BAICUNY2KYd%2Fi7r2khNs%3D; expires=Thu, 11 Nov 2021 00:00:00 GMT; path=/; secure; samesite=none; httponly",".WebUI.LangId=c%3Den-GB%7Cuic%3Den-GB; expires=Thu, 11 Nov 2021 23:00:46 GMT; path=/; secure; samesite=none",".AspNetCore.Session=CfDJ8E4%2B4dGULHpAolUZYg3jp4mfXOVXkS5GAaiTrSiqBAwMoOM4ofG6s0zhLEUeDH4SzvacVWupGDw2j0v2dqKs6iWmF3sjgsixoEmbrdKjn7sdwkEVIMGAFOUL2OGbsm4ZkclKFNragAtZKrqGHvhCP5jj3pCQBp7SgSnlDnOwEqRL; path=/; samesite=lax; httponly"]
Host: www.riscocloud.com
Referer: https://www.riscocloud.com/ELAS/WebUI/MainPage/MainPage
User-Agent: axios/0.19.2
Origin: https://www.riscocloud.com

(node:15503) UnhandledPromiseRejectionWarning: Bad HTTP Response: 500
Data: StackExchange.Redis.RedisTimeoutException: Timeout awaiting response (outbound=0KiB, inbound=20KiB, 10594ms elapsed, timeout is 10000ms), command=EVAL, next: EVAL, inst: 0, qu: 0, qs: 15, aw: False, rs: ReadAsync, ws: Idle, in: 0, serverEndpoint: RCWEPRD03-RED01.redis.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: RCWEPRD03-IIS06, IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=1,Free=32766,Min=2,Max=32767), v: 2.1.58.34321 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisExtensions.HashMemberGetAsync(IDatabase cache, String key, String[] members)
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.GetAndRefreshAsync(String key, Boolean getData, CancellationToken token)
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.GetAsync(String key, CancellationToken token)
   at Microsoft.AspNetCore.Session.DistributedSession.LoadAsync(CancellationToken cancellationToken)
   at WebUserUI.WrappedDistributedSession.LoadAsync(CancellationToken cancellationToken) in C:\BuildWS\workspace\RiscoCloud\riscocloud\release\WebUserUI\src\WrappedSession.cs:line 36
   at WebUICore.SessionHelpers.SessionGetAsync[T](HttpContext context, String key) in C:\BuildWS\workspace\RiscoCloud\riscocloud\release\WebUserUI\src\SessionHelpers.cs:line 32
   at WebUserUI.Models.UserData.GetCurrent(HttpContext context) in C:\BuildWS\workspace\RiscoCloud\riscocloud\release\WebUserUI\Models\UserData.cs:line 68
   at WebUserUI.Controllers.Security.SecurityController.GetCPState(Boolean userIsAlive) in C:\BuildWS\workspace\RiscoCloud\riscocloud\release\WebUserUI\Controllers\Security\SecurityController.cs:line 551
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Accept: application/json, text/plain, */*
Connection: close
Content-Length: 2
Content-Type: application/json;charset=utf-8
Cookie: ["RUCCookie=0owz3fEDm8P9ZO7yPKwGCv1%2BAICUNY2KYd%2Fi7r2khNs%3D; expires=Thu, 11 Nov 2021 00:00:00 GMT; path=/; secure; samesite=none; httponly",".WebUI.LangId=c%3Den-GB%7Cuic%3Den-GB; expires=Thu, 11 Nov 2021 23:00:46 GMT; path=/; secure; samesite=none",".AspNetCore.Session=CfDJ8E4%2B4dGULHpAolUZYg3jp4mfXOVXkS5GAaiTrSiqBAwMoOM4ofG6s0zhLEUeDH4SzvacVWupGDw2j0v2dqKs6iWmF3sjgsixoEmbrdKjn7sdwkEVIMGAFOUL2OGbsm4ZkclKFNragAtZKrqGHvhCP5jj3pCQBp7SgSnlDnOwEqRL; path=/; samesite=lax; httponly"]
Host: www.riscocloud.com
Referer: https://www.riscocloud.com/ELAS/WebUI/MainPage/MainPage
User-Agent: axios/0.19.2
Origin: https://www.riscocloud.com

(node:15503) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 72)
```

**Comment by andyblac** [comment]
started around 20:09 here the log.
[homebridge.log](https://github.com/gawindx/homebridge-risco-platform/files/5527365/homebridge.log)

**Comment by kellery82** [comment]
I'm having the exact same issue;

[11/12/2020, 8:54:28 AM] [Home Alarm] UserCodeExpired error:
Bad HTTP Response: 500
Data: StackExchange.Redis.RedisTimeoutException: Timeout awaiting response (outbound=0KiB, inbound=2KiB, 10750ms elapsed, timeout is 10000ms), command=EVAL, next: EVAL, inst: 0, qu: 0, qs: 18, aw: False, rs: ReadAsync, ws: Idle, in: 0, serverEndpoint: RCWEPRD03-RED01.redis.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: RCWEPRD03-IIS04, IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=1,Free=32766,Min=2,Max=32767), v: 2.1.58.34321 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisExtensions.HashMemberGetAsync(IDatabase cache, String key, String[] members)
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.GetAndRefreshAsync(String key, Boolean getData, CancellationToken token)
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.GetAsync(String key, CancellationToken token)
   at Microsoft.AspNetCore.Session.DistributedSession.LoadAsync(CancellationToken cancellationToken)
   at WebUserUI.WrappedDistributedSession.LoadAsync(CancellationToken cancellationToken) in C:\BuildWS\workspace\RiscoCloud\riscocloud\release\WebUserUI\src\WrappedSession.cs:line 36
   at WebUICore.SessionHelpers.SessionGetAsync[T](HttpContext context, String key) in C:\BuildWS\workspace\RiscoCloud\riscocloud\release\WebUserUI\src\SessionHelpers.cs:line 32
   at WebUserUI.Models.UserData.GetCurrent(HttpContext context) in C:\BuildWS\workspace\RiscoCloud\riscocloud\release\WebUserUI\Models\UserData.cs:line 68
   at WebUserUI.Controllers.SystemSettings.SystemSettingsController.IsUserCodeExpired() in C:\BuildWS\workspace\RiscoCloud\riscocloud\release\WebUserUI\Controllers\SystemSettings\SystemSettingsController.cs:line 1469
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Accept: application/json, text/plain, */*
Connection: close
Content-Length: 2
Content-Type: application/json;charset=utf-8
Cookie: ["RUCCookie=xcJj4%2FlZNRGnfxRhEmMOpB%2BDN8agzlOCYtxO6th%2F68M%3D; expires=Fri, 12 Nov 2021 00:00:00 GMT; path=/; secure; samesite=none; httponly",".WebUI.LangId=c%3Den-GB%7Cuic%3Den-GB; expires=Fri, 12 Nov 2021 00:32:48 GMT; path=/; secure; samesite=none",".AspNetCore.Session=CfDJ8E4%2B4dGULHpAolUZYg3jp4m6kJPkhLe3vDFD7q0emKdv0hxjxuf8V4gAb7ZpY1hqqPM2CGQ2Tfbd5I1MzTXvtr0xzi5CqYUtzZkt%2FTcRlPH1VleFRXIOUoqGb46K6iJ1kdXiRJ7VBO5P4DeuHk6UVhwpLMMc1YdN5fFiBrUQV%2BvL; path=/; samesite=lax; httponly"]
Host: www.riscocloud.com
Referer: https://www.riscocloud.com/ELAS/WebUI/MainPage/MainPage
User-Agent: axios/0.19.2
Origin: https://www.riscocloud.com

**Comment by gawindx** [comment]
unfortunately, this problem does not come from the plugin but from an error of the Risco servers (error 500)

the error is correctly handled on my side but, as long as the server does not respond correctly, I cannot do much about it (it is displayed only in the logs)

From what I could see in my logs, this error mainly occurs at night, which lets me think that, perhaps, some normal maintenance operations at Risco make certain web services inoperative or insufficient.

it will therefore be necessary to wait for Risco to solve this problem or, if it lasts over time, for me to proceed differently to maintain the connection.

**Comment by kellery82** [comment]
Thanks mate,  no worries 👍

**Comment by andyblac** [comment]
still getting this, and sometimes it stops arm / disarm in homekit, can you look into it working around the error ?

**Comment by gawindx** [comment]
I will try to analyze this problem but the main concern is that I do not encounter these errors.

I planned to release v1.2 soon; this version should provide support for combined accessories (managing both an entry and an exit).
I think I will shift the release of this version to make a major change in the cloud connection functions (the idea being to migrate web APIs to APIs used by the iRisco application).
I hope that the latter will not suffer from the same problems as the web interface but they seem to be faster for state changes anyway.

this modification will require a little time to "sniff" them and modify the code, so we will have to wait a bit.

**Comment by andyblac** [comment]
updated to 1.2.0 got this error:

```
[20/11/2020, 19:09:28] [RiscoAlarm] UserCodeExpired error:
Error on Request : -3001
[20/11/2020, 19:09:28] [RiscoAlarm] Error on Validate User Code:
1Error on Request : -3001
 Code : EAI_AGAIN
[20/11/2020, 19:09:28] [RiscoAlarm] Error on getCPStates: Error on Request : -3001
 Code : EAI_AGAIN
(node:22227) UnhandledPromiseRejectionWarning: Error on Request : -3001
 Code : EAI_AGAIN
(Use `node --trace-warnings ...` to show where the warning was created)
(node:22227) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
(node:22227) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[20/11/2020, 19:12:46] [RiscoAlarm] UserCodeExpired error:
Error on Request : -3001
[20/11/2020, 19:12:46] [RiscoAlarm] Error on Validate User Code:
1Error on Request : -3001
 Code : EAI_AGAIN
[20/11/2020, 19:12:46] [RiscoAlarm] Error on getCPStates: Error on Request : -3001
 Code : EAI_AGAIN
(node:22227) UnhandledPromiseRejectionWarning: Error on Request : -3001
 Code : EAI_AGAIN
(node:22227) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 16)
[20/11/2020, 19:16:10] [RiscoAlarm] UserCodeExpired error:
Error on Request : -3001
[20/11/2020, 19:16:10] [RiscoAlarm] Error on Validate User Code:
1Error on Request : -3001
 Code : EAI_AGAIN
[20/11/2020, 19:16:10] [RiscoAlarm] Error on getCPStates: Error on Request : -3001
 Code : EAI_AGAIN
(node:22227) UnhandledPromiseRejectionWarning: Error on Request : -3001
 Code : EAI_AGAIN
(node:22227) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 24)
[20/11/2020, 19:25:40] [RiscoAlarm] UserCodeExpired error:
Error on Request : -3001
[20/11/2020, 19:25:40] [RiscoAlarm] Error on Validate User Code:
1Error on Request : -3001
 Code : EAI_AGAIN
[20/11/2020, 19:25:40] [RiscoAlarm] Error on getCPStates: Error on Request : -3001
 Code : EAI_AGAIN
(node:22227) UnhandledPromiseRejectionWarning: Error on Request : -3001
 Code : EAI_AGAIN
(node:22227) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 32)
[20/11/2020, 20:09:35] [RiscoAlarm] Session Expired. ReLogin
[20/11/2020, 20:09:36] [RiscoAlarm] Logged In Cloud
[20/11/2020, 20:58:51] [RiscoAlarm] Partition "Garage" => New state detected: (1) -> AWAY_ARM. Notify!
[20/11/2020, 20:58:51] [RiscoAlarm] Partition Garage is not Occupied. Notify!
[20/11/2020, 21:10:04] [RiscoAlarm] Session Expired. ReLogin
[20/11/2020, 21:10:04] [RiscoAlarm] Logged In Cloud
[20/11/2020, 22:10:35] [RiscoAlarm] Session Expired. ReLogin
[20/11/2020, 22:10:36] [RiscoAlarm] Logged In Cloud
```

**Comment by gawindx** [comment]
v1.2.0 presented on github is not the final version which will be released as a package.

this version brings some additional functionalities such as the combined accessories (a detector associated with an output) but the recent changes made by risco force me to continue its development to avoid the errors that you encounter.
this is the main reason that prevented me from deploying this version on npm.

The development is well under way but the non documentation of the Risco APIs makes the task rather long and I still have a lot of tests to do to obtain a stable and perfectly functional result.

for those who have recovered v1.2.0 on github, do not update the package.json file (or modify it to indicate a version lower than v1.2.0) otherwise your package will not update with the final version .

**Comment by gawindx** [comment]
Small feedback to keep you informed of the development regarding this problem.
The last tests are in progress and, if no connection error appears in the next 48 hours (which I hope), version 1.2.0 should be released for this weekend.

I will also update the repository to save the code in the current state of development, but it remains a "beta" version as long as the last tests are not passed correctly.
You are free to recover the files in their current state, but they should be used with care.

**Comment by gawindx** [comment]
V1.2.0 is released.
No error for 24 hours when renewing the connection to the Cloud.

**Comment by gawindx** [comment]
I think this problem is no longer relevant, I close the issue but it can be reopened if necessary
