### ISSUE TITLE
can not arm / disarm

### ISSUE THREAD

**Issue by andyblac** [gawindx/homebridge-risco-platform#41]
i see following in homebridge logs
```
[27/02/2021, 07:18:54] [RiscoAlarm] Cloud Authentication Successfull
[27/02/2021, 07:18:54] [RiscoAlarm] Retrieving Cloud Session: Ok
[27/02/2021, 08:18:57] [RiscoAlarm] Retrieving Cloud Session: Ok
[27/02/2021, 09:08:28] [RiscoAlarm] Error on armDisarm function:
TypeError: Cannot read property 'partitions' of null
    at RiscoPanelSession.armDisarm (/usr/local/lib/node_modules/homebridge-risco-platform/Risco.js:1179:68)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at RiscoCPPartitions.GetSetArmState (/usr/local/lib/node_modules/homebridge-risco-platform/RiscoAccessories.js:371:38)
    at RiscoCPPartitions.setTargetState (/usr/local/lib/node_modules/homebridge-risco-platform/RiscoAccessories.js:272:47)
[27/02/2021, 09:08:39] [RiscoAlarm] Contact Sensor "Kitchen Door" => New state detected: (Active). Notify!
[27/02/2021, 09:08:39] [RiscoAlarm] Contact Sensor "Kitchen Door" => New Bypass State detected : (Not ByPassed). Notify!
```
just started last night, if i arm / disarm via alarm panel status is updated fine in homekit.

**Comment by andyblac** [comment]
back working must have been a risco issue.
