### ISSUE TITLE
Disarm doesn't work

### ISSUE THREAD

**Issue by evgolsh** [gawindx/homebridge-risco-platform#46]
Hello. Thank you for the plugin (I did read reasons of stopping maintenance of this plugin).

Everything works just fine except for disarming the system. I get the following log:

`[25/05/2022, 16:37:09] [RiscoAlarm] Error on getAlarmState:
TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at /usr/lib/node_modules/homebridge-risco-platform/Risco.js:742:36
    at Array.map (<anonymous>)
    at RiscoPanelSession.getAlarmState (/usr/lib/node_modules/homebridge-risco-platform/Risco.js:733:18)
    at RiscoPanelSession.UpdateCPStates (/usr/lib/node_modules/homebridge-risco-platform/Risco.js:1116:70)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
[25/05/2022, 16:37:09] [RiscoAlarm] Error on UpdateCPStates: undefined`

**Comment by evgolsh** [comment]
Tried to debug it. The error I mentioned pops only there is an alarm. It sends disarm command successfully but it keeps in the armed state silently. Any thoughts?
